"""
ConservativeBaseLp Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import ConservativeBaseLpStrategy
except ImportError:
    from strategy import ConservativeBaseLpStrategy

__all__ = ["ConservativeBaseLpStrategy"]
